[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Content-Security-Policy = "connect-src *; default-src 'self'; frame-ancestors 'self' *.pnfc.re; frame-src 'self' *.pnfc.re; img-src 'self' data: *.discord.com *.discordapp.com; script-src 'self' storage.googleapis.com; style-src 'self' 'unsafe-inline'"

[[headers]]
  for = "/cb.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'"

[[redirects]]
  status = 301
  force = true
  to = "https://play.pnfc.re/:splat"
  from = "https://zeiw.netlify.com/*"

[[redirects]]
  status = 200
  force = true
  from = "/api/*"
  to = "https://api.pnfc.re/:splat"